// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef CERBERUS_PCR_H_
#define CERBERUS_PCR_H_

#include "attestation/pcr_store.h"


/**
 * Platform configuration register banks
 */
enum {
	PCR_CERBERUS_PLATFORM = 0,							/**< Measurement for Cerberus platform */
	PCR_CERBERUS_MANIFESTS,								/**< Measurement for Cerberus configuration */
	PCR_CERBERUS_NUM_BANKS								/**< Number of PCR banks supported */
};

/**
 * Platform configuration register measurements per bank
 */
#define PCR_CERBERUS_PLATFORM_MEASUREMENTS		9		/**< Number of platform measurements */

#ifdef CERBERUS_ENABLE_COMPONENT_ATTESTATION
#define PCR_CERBERUS_MANIFESTS_MEASUREMENTS		7		/**< Number of manifest measurements */
#endif

/**
 * PCR measurement types
 */
enum {
	PCR_MEASUREMENT_TYPE_PLATFORM_BOOT_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 0),
	PCR_MEASUREMENT_TYPE_PLATFORM_APP_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 1),
	PCR_MEASUREMENT_TYPE_PLATFORM_FW_VERSION = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 2),
	PCR_MEASUREMENT_TYPE_PLATFORM_KMT_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 3),
	PCR_MEASUREMENT_TYPE_PLATFORM_SKMT_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 4),
	PCR_MEASUREMENT_TYPE_PLATFORM_BB_IMG =  PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 5),
	PCR_MEASUREMENT_TYPE_PLATFORM_BL31_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 6),
	PCR_MEASUREMENT_TYPE_PLATFORM_OPTEE_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 7),
	PCR_MEASUREMENT_TYPE_PLATFORM_UBOOT_IMG = PCR_MEASUREMENT (PCR_CERBERUS_PLATFORM, 8),
#ifdef CERBERUS_ENABLE_COMPONENT_ATTESTATION
	PCR_MEASUREMENT_TYPE_CONFIG_PCD = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 0),
	PCR_MEASUREMENT_TYPE_CONFIG_PCD_ID = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 1),
	PCR_MEASUREMENT_TYPE_CONFIG_PCD_PLATFORM_ID = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 2),
	PCR_MEASUREMENT_TYPE_CONFIG_CFM = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 3),
	PCR_MEASUREMENT_TYPE_CONFIG_CFM_VALID = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 4),
	PCR_MEASUREMENT_TYPE_CONFIG_CFM_ID = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 5),
	PCR_MEASUREMENT_TYPE_CONFIG_CFM_PLATFORM_ID = PCR_MEASUREMENT (PCR_CERBERUS_MANIFESTS, 6),
#endif
};


#endif /* CERBERUS_PCR_H_ */
