// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license.

#ifndef PCR_TCG_H_
#define PCR_TCG_H_

/**
 * PCR TCG event types
 */
enum {
	PCR_TCG_EVENT_TYPE_PLATFORM_BOOT_IMG = 0,
	PCR_TCG_EVENT_TYPE_PLATFORM_APP_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_CERBERUS_FW_VERSION,
	PCR_TCG_EVENT_TYPE_PLATFORM_KMT_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_SKMT_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_BB_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_BL31_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_OPTEE_IMG,
	PCR_TCG_EVENT_TYPE_PLATFORM_UBOOT_IMG,
};


#endif /* PCR_TCG_H_ */
