/*---------------------------------------------------------------------------------------------------------*/
/*  Nuvoton Technology Corporation Confidential                                                            */
/*                                                                                                         */
/*  Copyright (c) 2010-2018 by Nuvoton Technology Corporation                                              */
/*  All rights reserved                                                                                    */
/*                                                                                                         */
/*<<<------------------------------------------------------------------------------------------------------*/
/* File Contents:                                                                                          */
/*   twd_if.h                                                                                              */
/*            This file contains Timer Watch-Dog (TWD) interface                                           */
/* Project:                                                                                                */
/*            SWC HAL                                                                                      */
/*---------------------------------------------------------------------------------------------------------*/
#ifndef _TWD_IF_H
#define _TWD_IF_H

/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/
/*                                                 INCLUDES                                                */
/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/
#include __CHIP_H_FROM_IF()

#if defined TWD_MODULE_TYPE
#include __MODULE_HEADER(twd, TWD_MODULE_TYPE)
#endif


/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/
/*                                           TYPES & DEFINITIONS                                           */
/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/

#ifdef TWD_NO_INTERRUPT
#undef TWD_CAPABILITY_TWD_INTERRUPT_EN
#endif

/*---------------------------------------------------------------------------------------------------------*/
/* Watch-Dog Source Clock                                                                                  */
/*---------------------------------------------------------------------------------------------------------*/
typedef enum {
    TIMER_OUT   = 0,
    TIMER_IN
} TWD_WD_SOURCE_T;

/*---------------------------------------------------------------------------------------------------------*/
/* Type of reset generated by a watchdog event                                                             */
/*---------------------------------------------------------------------------------------------------------*/
typedef enum {
    COLD_RESET              = 0,
    WARM_RESET              = 1,
#ifdef TWD_CAPABILITY_VCC_POR_RESET
    COLD_RESET_WITH_VCC_POR = 2,
#endif
} TWD_WD_RESET_T;

/*---------------------------------------------------------------------------------------------------------*/
/* Timer Callback function                                                                                 */
/*---------------------------------------------------------------------------------------------------------*/
typedef void (*TWD_CALLBACK)(void);

/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/
/*                                           INTERFACE FUNCTIONS                                           */
/*---------------------------------------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_Init                                                                               */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  timer_handler - application callback to be called from timer interrupt handler.        */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine initializes the TWD module.                                               */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_Init (TWD_CALLBACK timer_handler);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerConfig_us                                                                     */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  time - desired system tick time in usec.                                               */
/*                                                                                                         */
/* Returns:         DEFS Error code.                                                                       */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine sets the timer to "time" microseconds.                                    */
/*                  It is assumed that the core is running in a frequency, sufficuent to track RST         */
/*                  toggling before start counting (guaranteed by design).                                 */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_TimerConfig_us (UINT16 time);


/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerConfig                                                                        */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  time - desired system tick time in msec.                                               */
/*                                                                                                         */
/* Returns:         DEFS Error code.                                                                       */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine sets the timer to "time" milliseconds.                                    */
/*                  It is assumed that the core is running in a frequency, sufficuent to track RST         */
/*                  toggling before start counting (guaranteed by design).                                 */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_TimerConfig (UINT16 time);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerGetMdiv                                                                       */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         mdiv value.                                                                            */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine returns the current value of the pre-scale ratio (TWCP.MDIV) of the input */
/*                  clock.                                                                                 */
/*---------------------------------------------------------------------------------------------------------*/
UINT8 TWD_TimerGetMdiv (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerConfigLock                                                                    */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  config_lock   - if TRUE locks (write protected) TWD module configuration (TWCFG).      */
/*                  prescale_lock - if TRUE locks (write protected) the pre-dcale ratio (TWCP.MDIV).       */
/*                  counter_lock  - if TRUE locks (write protected) TWDT0 counter and it's                 */
/*                                  control & status register (T0CSR).                                     */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine locks (write protected) configurations.                                   */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_TimerConfigLock (BOOLEAN config_lock, BOOLEAN prescale_lock, BOOLEAN counter_lock);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatcDogConfig                                                                      */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  preset     - WD counter value.                                                         */
/*                  source     - Source clock for WD - T0IN/T0OUT.                                         */
/*                  reset      - Type of reset generated by a watchdog event.                              */
/*                  data_match - Boolean indicating whether to use Data Match machanism.                   */
/*                  wdiv       - watch-dog prescaler value.                                                */
/*                                                                                                         */
/* Returns:         DEFS Error code.                                                                       */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine configures the WD service - counter value, source clock and whether to    */
/*                  use data match mechanism.                                                              */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_WatchDogConfig (UINT8 preset, TWD_WD_SOURCE_T source,TWD_WD_RESET_T reset, BOOLEAN data_match,
                                UINT8 wdiv);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogStart                                                                      */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  ms - number of milliseconds                                                            */
/*                                                                                                         */
/* Returns:         DEFS_STATUS_OK if the TWD was set correctly, otherwise returns DEFS_STATUS_FAIL        */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  Start the WatchDog countdown with the "ms" milliseconds.                               */
/*                  Support up to 65 seconds (65535 ms) however note that:                                 */
/*                  if ms <= 256 the timer resolution is 1ms                                               */
/*                  if   2^n =< ms < 2^(n+1)  the resolution is +- 2^(n-7) ms                              */
/*                  if   512 =< ms < 1024  the resolution is up to +-4ms                                   */
/*                  if  1024 =< ms < 2048  the resolution is up to +-8ms                                   */
/*                  if  2048 =< ms < 4096  the resolution is up to +-16ms                                  */
/*                  if  4096 =< ms < 8192  the resolution is up to +-32ms                                  */
/*                  if  8192 =< ms < 16384 the resolution is up to +-64ms                                  */
/*                  if 16384 =< ms < 32768 the resolution is up to +-128ms                                 */
/*                  if 32768 =< ms < 65536 the resolution is up to +-256ms                                 */
/*                  For example setting ms to count to 5000ms will result in 4992 ms , since it is the     */
/*                  closest number to 5000 which can be divided to 32ms ("the resolution")                 */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_WatchDogStart (UINT16 ms);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_DisableTooEarlyTouch                                                               */
/*                                                                                                         */
/* Parameters:      disVal - TRUE : To Disable the "Too Early Touch" mechanism                             */
/*                         - FALSE: To Ebable the "Too Early Touch" mechanism                              */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  Disables (or enable) the WD "Too Early Touch" mechanism                                */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_DisableTooEarlyTouch(BOOLEAN disVal);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogConfigLock                                                                 */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine locks (write protected) WD count register (WDCNT).                        */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_WatchDogConfigLock (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogRestart                                                                    */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine restarts/touches the WD service.                                          */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_WatchDogRestart (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogUpdate                                                                     */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  preset - new WD count down value.                                                      */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine Update the WD count-down value.                                           */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_WatchDogUpdate (UINT8 preset);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogStop                                                                       */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine stops watchdog operation by performing a stop sequence.                   */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_WatchDogStop (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_UnlockRegisters                                                                    */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine unlocks TWD registers if they have been locked.                           */
/*                  Note that watchdog mechanism should be stopped before unlocking TWD registers.         */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_UnlockRegisters (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogResetOccurred                                                              */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         TRUE in case Watch-Dog reset was generated; FALSE otherwise.                           */
/* Side effects:    In case Watch-Dog reset occurred, clear the Watch-Dog Reset Status bit.                */
/* Description:                                                                                            */
/*                  This routine checks whether a Watch-Dog reset occurred.                                */
/*---------------------------------------------------------------------------------------------------------*/
BOOLEAN TWD_WatchDogResetOccurred (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogResetClearEvent                                                            */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none.                                                                                  */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine clears the Watch-Dog Reset Status bit.                                    */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_WatchDogResetClearEvent (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerHandler                                                                       */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  int_num - number of triggered interrupt                                                */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  System Tick handler function - invokes the application callback function,              */
/*                  and clears the interrupt.                                                              */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_TimerHandler (UINT16 int_num);

#ifdef TWD_CAPABILITY_TIMER_READ_COUNTER
/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerGetCounter                                                                    */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         Timer counter value.                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine returns the value of the T0OUT counter (TWMT0).                           */
/*---------------------------------------------------------------------------------------------------------*/
UINT16 TWD_TimerGetCounter (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerTimeRemaining                                                                 */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  time - remaining time in msec ptr.                                                     */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine returns the time remaining until the T0 counter reaches 0.                */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_TimerTimeRemaining (UINT32* time);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_TimerTimeRemaining_us                                                              */
/*                                                                                                         */
/* Parameters:                                                                                             */
/*                  time - remaining time in usec ptr.                                                     */
/*                                                                                                         */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine returns the time remaining until the T0 counter reaches 0.                */
/*---------------------------------------------------------------------------------------------------------*/
DEFS_STATUS TWD_TimerTimeRemaining_us (UINT32* time);
#endif

#ifdef TWD_CAPABILITY_WD_READ_COUNTER
/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogGetCounter                                                                 */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         Watchdog counter value.                                                                */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine returns the value of the WDCNT counter (TWMWD).                           */
/*---------------------------------------------------------------------------------------------------------*/
UINT8 TWD_WatchDogGetCounter (void);
#endif

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogIsRunning                                                                  */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         TRUE  - WatchDog is enabled and running (counting down).                               */
/*                  FALSE - otherwise                                                                      */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine checks & returns is the WatchDog is running or not                        */
/*---------------------------------------------------------------------------------------------------------*/
BOOLEAN TWD_WatchDogIsRunning (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_WatchDogTouched                                                                    */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         TRUE in case Watch-Dog was "touched"; FALSE otherwise.                                 */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine checks whether a valid Watch-Dog "touch" operation is now performed.      */
/*                  This is important when switching to Idle or Deep Idle mode.                            */
/*---------------------------------------------------------------------------------------------------------*/
BOOLEAN TWD_WatchDogTouched (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_PrintRegs                                                                          */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine prints the module registers                                               */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_PrintRegs (void);

/*---------------------------------------------------------------------------------------------------------*/
/* Function:        TWD_PrintVersion                                                                       */
/*                                                                                                         */
/* Parameters:      none                                                                                   */
/* Returns:         none                                                                                   */
/* Side effects:                                                                                           */
/* Description:                                                                                            */
/*                  This routine prints the module version                                                 */
/*---------------------------------------------------------------------------------------------------------*/
void TWD_PrintVersion (void);

#endif  /* _TWD_IF_H */

