/* SPDX-License-Identifier: Apache-2.0 */
/* Copyright (c) 2026 Nuvoton Technology Corporation. */

#ifndef BMC_DIRECT_COMPOSITE_EAT_ABI_H_
#define BMC_DIRECT_COMPOSITE_EAT_ABI_H_

#include <stdint.h>


#define BMC_DIRECT_COMPOSITE_EAT_ABI_VERSION 1u
#define BMC_DIRECT_NOTIFICATION_COMPOSITE_EAT 0x10u
#define BMC_DIRECT_COMMAND_COMPOSITE_EAT 0x11u
#define BMC_DIRECT_COMPOSITE_EAT_TASK_EVENT 0x100u

#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_COMMAND 24u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_REQ_ADDR 25u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_REQ_LEN 26u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_RESP_ADDR 27u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_RESP_CAP 28u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_RESP_LEN 29u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_REQUEST_ID 30u
#define BMC_DIRECT_COMPOSITE_EAT_SCRPAD_RESPONSE_ID 31u

#define BMC_DIRECT_COMPOSITE_EAT_SHM_BASE 0x06201000u
#define BMC_DIRECT_COMPOSITE_EAT_REQ_OFFSET 0x00000000u
#define BMC_DIRECT_COMPOSITE_EAT_REQ_SIZE 0x00001000u
#define BMC_DIRECT_COMPOSITE_EAT_RESP_OFFSET BMC_DIRECT_COMPOSITE_EAT_REQ_SIZE
#define BMC_DIRECT_COMPOSITE_EAT_RESP_SIZE 0x00004000u

enum bmc_direct_composite_eat_status {
	BMC_DIRECT_COMPOSITE_EAT_OK = 0,
	BMC_DIRECT_COMPOSITE_EAT_BAD_VERSION = 1,
	BMC_DIRECT_COMPOSITE_EAT_BAD_REQUEST = 2,
	BMC_DIRECT_COMPOSITE_EAT_TOO_MANY_RECORDS = 3,
	BMC_DIRECT_COMPOSITE_EAT_REQUEST_TOO_LARGE = 4,
	BMC_DIRECT_COMPOSITE_EAT_RESPONSE_TOO_SMALL = 5,
	BMC_DIRECT_COMPOSITE_EAT_ADDRESS_INVALID = 6,
	BMC_DIRECT_COMPOSITE_EAT_SIGN_FAILED = 7,
	BMC_DIRECT_COMPOSITE_EAT_BUSY = 8,
	BMC_DIRECT_COMPOSITE_EAT_INTERNAL = 9,
	BMC_DIRECT_COMPOSITE_EAT_UNSUPPORTED = 10,
};


#endif /* BMC_DIRECT_COMPOSITE_EAT_ABI_H_ */