/*---------------------------------------------------------------------------------------------------------*/
/*  Copyright (c) 2026 by Nuvoton Technology Corporation.                                                       */
/*  SPDX-License-Identifier: Apache-2.0                                                                                              */
/*<<<---------------------------------------------------------------------------------------------------*/

#ifndef TIP_AES_NCL_H_
#define TIP_AES_NCL_H_

#include "crypto/aes_gcm.h"
#include "status/tip_module_id.h"
#include "tip_security.h"
#include "tip_rom_ncl_shared_state.h"


/**
 * An TIP NCL context for AES operations.
 */
struct tip_aes_ncl_engine {
	struct aes_gcm_engine base;						/**< The base AES engine. */
	uint8_t context[NCL_AES_CONTEXT_BYTE_SIZE]; 	/**< Context for AES-GCM operations. */
	NCL_AES_KEY_SIZE_T key_size;					/**< the AES key size */
	NCL_AES_MODE_T aes_mode;						/**< the type of AES mode (GCM\CCM) */
	uint8_t key_ind;								/**< the AES relevant key index */
	int (*set_mode) (struct tip_aes_ncl_engine *engine, NCL_AES_MODE_T mode);
	int (*select_key) (struct tip_aes_ncl_engine *engine, uint8_t key_num);
	struct tip_rom_ncl_shared_state *shared_state;			/**< Shared state for synchronization. */
};

int tip_aes_ncl_init (struct tip_aes_ncl_engine *engine, struct tip_rom_ncl_shared_state *shared_state);
void tip_aes_ncl_release (struct tip_aes_ncl_engine *engine);


#define	TIP_NCL_AES_ENGINE_ERROR(code)		ROT_ERROR (TIP_NCL_AES_ENGINE, code)

/**
 * Error codes that can be generated by TIP NCL AES-GCM engine.
 */
enum {
	TIP_AES_ENGINE_INVALID_ARGUMENT = TIP_NCL_AES_ENGINE_ERROR (0x00),			/**< Input parameter is null or not valid. */
	TIP_AES_ENGINE_NO_MEMORY = TIP_NCL_AES_ENGINE_ERROR (0x01),					/**< Memory allocation failed. */
	TIP_AES_ENGINE_SET_KEY_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x02),			/**< The encryption key could not be set. */
	TIP_AES_ENGINE_ENCRYPT_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x03),			/**< The plaintext was not encrypted. */
	TIP_AES_ENGINE_DECRYPT_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x04),			/**< The ciphertext was not decrypted. */
	TIP_AES_ENGINE_UNSUPPORTED_KEY_LENGTH = TIP_NCL_AES_ENGINE_ERROR (0x05),	/**< The encryption key length is not supported by the engine. */
	TIP_AES_ENGINE_INVALID_KEY_LENGTH = TIP_NCL_AES_ENGINE_ERROR (0x06),		/**< The key length is not a valid AES key length. */
	TIP_AES_ENGINE_OUT_BUFFER_TOO_SMALL = TIP_NCL_AES_ENGINE_ERROR (0x07),		/**< Not enough space in an output buffer provided for the operation. */
	TIP_AES_ENGINE_NO_KEY = TIP_NCL_AES_ENGINE_ERROR (0x08),					/**< No key was set prior to encryption/decryption. */
	TIP_AES_ENGINE_GCM_AUTH_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x09),			/**< The decrypted plaintext failed authentication. */
	TIP_AES_ENGINE_HW_NOT_INIT = TIP_NCL_AES_ENGINE_ERROR (0x0a),				/**< The AES hardware has not been initialized. */
	TIP_AES_ENGINE_SELF_TEST_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x0b),			/**< An internal self-test of the AES engine failed. */
	TIP_AES_ENGINE_UNSUPPORTED_OPERATION = TIP_NCL_AES_ENGINE_ERROR (0x0c),		/**< The requested operation is not supported. */
	TIP_AES_ENGINE_ENCRYPT_ADD_DATA_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x0d),	/**< The plaintext with additional data was not encrypted. */
	TIP_AES_ENGINE_DECRYPT_ADD_DATA_FAILED = TIP_NCL_AES_ENGINE_ERROR (0x0e),	/**< The ciphertext with additional data was not decrypted. */
};


#endif /* TIP_AES_NCL_H_ */
